In [1]:
import numpy as np

In [2]:
data = [1,2,3]
np.array(data)

array([1, 2, 3])

In [3]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [4]:
np.arange(1, 10) * 3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [5]:
np.arange(2, 100, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [6]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [7]:
data = [0, 1, 2, 3, 4, 5]
data = np.array(data)
data.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
arr = np.array([
    [0,1,2],
    [3,4,5]
])

print(arr.reshape(6))
print(arr.flatten())

[0 1 2 3 4 5]
[0 1 2 3 4 5]


In [9]:
arr = np.arange(3)
arr.reshape(3, 1)

array([[0],
       [1],
       [2]])

In [10]:
np.arange(6).reshape(2,3)


array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
np.ones(20, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [12]:
np.ones(20, dtype=int).reshape(4,5)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
np.ones(100, dtype=int).reshape(10,10) * 255

array([[255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255]])

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.arange(1,4,dtype=np.int32)

array([1, 2, 3], dtype=int32)

In [16]:
np.array([1,2,3]).dtype

dtype('int64')

In [17]:
np.array(['1','2','3']).dtype

dtype('<U1')

In [18]:
arr = np.array([1,2,3])
arr.astype(np.int16)

array([1, 2, 3], dtype=int16)

In [19]:
300-2**8

44

In [20]:
arr = np.array([1.1, 2.1, 3.1])
arr = arr.astype(np.int32)
arr

array([1, 2, 3], dtype=int32)

In [21]:
np.linspace(0,10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [22]:
arr = np.arange(9).reshape(3,3)
arr[-1]

array([6, 7, 8])

In [23]:
arr[:,1]

array([1, 4, 7])

In [24]:
arr = np.arange(25).reshape(5,5)
arr[3,2]

17

In [25]:
arr = np.arange(5)
arr[1:4:2]

array([1, 3])

In [26]:
arr = np.arange(25).reshape(5,5)
arr[1,1:]

array([6, 7, 8, 9])

In [27]:
arr = np.arange(25).reshape(5,5)
arr[:,:2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]])

In [28]:
arr = np.arange(25).reshape(5,5)
arr[1:3, 1:3]

array([[ 6,  7],
       [11, 12]])

In [29]:
arr[::4, ::3]

array([[ 0,  3],
       [20, 23]])

In [30]:
data = [1,2,3]
data = np.array(data) * 10
data

array([10, 20, 30])

In [31]:
data = np.array([1,2,3])
data ** 2

array([1, 4, 9])

In [32]:
data = np.array([1,2,3])
print(data ** 0.5)
print(np.sqrt(data))

[1.         1.41421356 1.73205081]
[1.         1.41421356 1.73205081]


In [33]:
score = np.array([
    [10,20],
    [14,16]
])

In [34]:
score.mean(axis=0)

array([12., 18.])

In [35]:
score = np.array([
    [10, 20],
    [14, 16],
])

score.std(axis=1)

array([5., 1.])

In [36]:
a = np.arange(4).reshape(2,2)
b = np.arange(1,5).reshape(2,2)

a@b
np.matmul(a,b)

array([[ 3,  4],
       [11, 16]])

In [37]:
arr = np.arange(9).reshape(3,3)
arr.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [38]:
arr =np.arange(10)
arr[::2]

array([0, 2, 4, 6, 8])

In [39]:
arr[1::2]

array([1, 3, 5, 7, 9])

In [40]:
arr[(arr>3) & (arr < 7)]

array([4, 5, 6])

In [41]:
arr = np.array([-1,2,-3,4])
arr[arr<0]

array([-1, -3])

In [42]:
arr[arr<0] = 0

In [43]:
arr = np.array([-1,2,-3,4])
arr[arr<0] = -arr[arr<0]
print(arr)
abs(arr)

[1 2 3 4]


array([1, 2, 3, 4])

In [44]:
arr = np.array([-1,2,-3,4])
arr[arr<0]=arr[arr<0]-10
arr[arr>0]=arr[arr>0]+10

np.where(arr>=0, arr+10, arr-10)

array([-21,  22, -23,  24])

In [45]:
arr = np.array([1,2,3,4,5])
np.random.shuffle(arr)
arr

array([2, 3, 4, 1, 5])

In [46]:
arr = np.array([1,2,3,4,5])
np.argmin(arr)

0

In [47]:
arr = np.array([1, 2, 3, 4, 5])
np.argmax(arr)

4

In [48]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
arr1=np.array([1,2])
arr2=np.array([3,4])
np.vstack((arr1,arr2))

array([[1, 2],
       [3, 4]])

In [50]:
np.array([[1,2],[3,4]]).flatten()


array([1, 2, 3, 4])