In [1]:
import numpy as np

In [2]:
a = np.array([[10, 20, 30, 40],
            [50, 60, 70, 80]])

In [3]:
m = np.array([[0,  1,  2,  3,  4],
            [5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

In [4]:
m[1][2]

7

In [5]:
m[-1,-1]

14

In [6]:
m[1,1:3]

array([6, 7])

In [7]:
m[1:,2]

array([ 7, 12])

In [8]:
m[:2,3:]

array([[3, 4],
       [8, 9]])

In [9]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [10]:
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [11]:
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [12]:
x[(x % 3 == 0) & (x % 4 == 1)]

array([9])

In [13]:
x = np.array([1,2,3], dtype='U')
x[0] + x[1]

'12'

In [14]:
a1 = np.hstack([np.zeros((3, 3)), np.ones((3, 2))])
a2 = np.arange(10, 160, 10, dtype='f8').reshape(3, 5)
np.tile(np.vstack([a1, a2]), (2,1))


array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [15]:
a = np.arange(30).reshape(5, 6)

print(a.max())
print(a.sum(axis=1))
print(a.max(axis=1))
print(a.mean(axis=0))
print(a.min(axis=0))

29
[ 15  51  87 123 159]
[ 5 11 17 23 29]
[12. 13. 14. 15. 16. 17.]
[0 1 2 3 4 5]


In [16]:
a = np.array([[1,    2,    3,    4],
       [46,   99,  100,   71],
       [81,   59,   90,  100]])

In [17]:
j = np.argsort(a[1,:])
j

array([0, 3, 1, 2])

In [18]:
a[:,j]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [19]:
dice = np.random.randint(0, 2, size=10)
print(dice)
print(np.random.randint(0, 2, size=100).mean())

[0 0 1 1 0 0 1 0 0 1]
0.47


In [20]:
stock = [10000]
for i in range(250):
    ratio_return = np.random.randn()
    stock.append(stock[i] * (1 + (ratio_return / 100)))
    
print(stock[250])

10269.16245937424
