In [5]:
import torch
import numpy as np

In [7]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [8]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array) #numpy -> torch
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [11]:
print(x_np.numpy())  #torch -> numpy

[[1 2]
 [3 4]]


In [13]:
x_ones = torch.ones_like(x_np)
x_rand = torch.rand_like(x_np, dtype=torch.float)

print(f"Ones Tensor: \n {x_ones} \n")
print(f"Rands Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Rands Tensor: 
 tensor([[0.8685, 0.6747],
        [0.9934, 0.9108]]) 



In [16]:
shape = (2, 3,) #텐서의 dimension을 나타내는 tuple. 아래 함수에서 출력 텐서의 차원을 결정
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeors Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.8769, 0.9699, 0.6929],
        [0.9052, 0.9951, 0.4317]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeors Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [17]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"DataType of tensor : {tensor.dtype}")
print(f"Device tensor is stored on : {tensor.device}")

Shape of tensor: torch.Size([3, 4])
DataType of tensor : torch.float32
Device tensor is stored on : cpu


In [18]:
# 텐서 연산 https://pytorch.org/docs/stable/torch.html
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print(f"Device tensor is stored on : {tensor.device}")

Device tensor is stored on : cuda:0


In [19]:
tensor = torch.ones(4, 4)
tensor[:,2] = 0
print(tensor)

tensor([[1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.]])


In [23]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
t2 = torch.cat([tensor, tensor, tensor], dim=0)

print(t1)
print(t2)

tensor([[1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1.],
        [1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1.],
        [1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1.],
        [1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1.]])
tensor([[1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.]])


In [24]:
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
print(f"tensor * tensor \n {tensor * tensor}") 

tensor.mul(tensor) 
 tensor([[1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.]]) 

tensor * tensor 
 tensor([[1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.]])


In [25]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [28]:
print(tensor, "\n")
tensor.add_(5) #접미사를 갖는 연산은 바꿔치기 연산(in-place)
print(tensor)

# x.copy_(), x.t_()
# In-place 연산은 메모리를 일부 절약하지만,
# 기록이 즉시 삭제되어 도함수 계산에 문제가 발생할 수 있음
# --> 권장 x


tensor([[11., 11., 10., 11.],
        [11., 11., 10., 11.],
        [11., 11., 10., 11.],
        [11., 11., 10., 11.]]) 

tensor([[16., 16., 15., 16.],
        [16., 16., 15., 16.],
        [16., 16., 15., 16.],
        [16., 16., 15., 16.]])


In [29]:
# CPU 상의 텐서와 넘파이 배열은 같은 메모리공간을 공유!
# 하나를 변경하면 다른 하나도 변경됨
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [31]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [32]:
n = np.ones(5)
t = torch.from_numpy(n)

In [33]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
